spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skills-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zaq1@WSX
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  application:
    name: skills-service
    ## Kafka properties
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:com.pwojcieszak.skillsService.event.SkillCreatedEvent
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

## Micrometer and Zipkin settings
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
## Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
