INSERT INTO skills (id, category, description, name) VALUES (20, 'Language', 'Native', 'Polish'),
                                                                                       (21, 'Language', 'C1', 'English'),
                                                                                       (22, 'Language', 'A2', 'German'),
                                                                                       (23, 'Coding', 'It was my first coding language, I used it on plenty on occasions during studies and high school', 'C++'),
                                                                                       (24, 'Coding', 'I used Python for data analysis and visualization', 'Python'),
                                                                                       (25, 'Web Design', 'During high school, our web development subjects focused on using these languages', 'HTML, CSS, plain JS'),
                                                                                       (26, 'Web Design', 'Used during apprenticeship during which I created two static websites, one mentioned in "Experience" section', 'WordPress'),
                                                                                       (27, 'Coding', 'Solid foundation, multithreading, synchronization, inheritance, interfaces, abstract classes', 'Java'),
                                                                                       (28, 'Frameworks', 'Spring Boot, Spring Security, JPA, Thymeleaf', 'Spring'),
                                                                                       (29, 'Frameworks', 'Netflix Eureka, API Gateway, Zipkin, Micrometer, Kafka, Grafana', 'Microservices Frameworks'),
                                                                                       (30, 'Development', 'Knowledge of creating multistage Dockerfiles, dockercompose, integrating with dockerhub', 'Docker'),
                                                                                       (31, 'Databases', 'Used during database classes in high school', 'MySQL');