spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skills-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zaq1@WSX
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: skills-service
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

## Micrometer and Zipkin settings
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"
    

