spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skills-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zaq1@WSX
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: skills-service

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
